apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx2_app
  template:
    metadata:
      labels:
        app: nginx2_app
    spec:
      containers:
        - name: hi
          image: nginx:latest
          ports:
            - containerPort: 80
              hostPort: 8080
