- hosts: kubernetes
  tasks:
    - name: Add machines to hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop:
        - 192.168.100.120 kubemaster
        - 192.168.100.121 kube2
        - 192.168.100.122 kube3

    - name: Disable swapoff
      shell: swapoff -a

    - name: Disable swap at fstab file
      replace:
        path: /etc/fstab
        regexp: "^/swap"
        replace: "#/swap"

    - name: Install required packages
      apt:
        name: "{{ item }}"
      loop:
        - python-apt
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add an Docker Apt signing key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker CE repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        update_cache: yes

    - name: Install Docker CE
      apt:
        name: "{{ item }}"
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Add an Kubernetes Apt signing key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        update_cache: yes

    - name: Install kubelet, kubeadm on all nodes
      apt:
        name: "{{ item }}"
      loop:
        - kubelet
        - kubeadm
        - kubectl